### ISSUE TITLE
Error while compiling to python

### ISSUE THREAD

**Issue by FarisAzka** [AeonLucid/POGOProtos#190]
I'm using python 2.7 and get this error

D:\TMP\PogoProto>d:\Python27\python compile_pretty.py python
Traceback (most recent call last):
  File "compile_pretty.py", line 450, in <module>
    call(command, shell=(os.name != 'nt'))
  File "d:\Python27\lib\subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "d:\Python27\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "d:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

How do i fix this?

**Comment by prodigion** [comment]
Place the protoc.exe from google in the same folder.

**Comment by FarisAzka** [comment]
Thanks. Downloaded protoc3 and it's solved
