### ISSUE TITLE
PokeNewb Problem

### ISSUE THREAD

**Issue by Gatopaint** [AeonLucid/POGOProtos#229]
gatopaint@gatopaint-VirtualBox:~/pokemon-go-mitm-node$ sudo npm start

> pokemon-go-mitm@2.1.0 start /home/gatopaint/pokemon-go-mitm-node
> coffee example.logTraffic.coffee

Error: Cannot find module 'http-mitm-proxy'
  at Function.Module._resolveFilename (module.js:455:15)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.exports.run (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! pokemon-go-mitm@2.1.0 start: `coffee example.logTraffic.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokemon-go-mitm@2.1.0 start script 'coffee example.logTraffic.coffee'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-go-mitm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee example.logTraffic.coffee
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-go-mitm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-go-mitm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gatopaint/pokemon-go-mitm-node/npm-debug.log

**Comment by Grover-c13** [comment]
Post on the mitm repo

**Comment by Gatopaint** [comment]
which is? @Grover-c13

**Comment by trisk** [comment]
@Gatopaint  http://github.com/rastapasta/pokemon-go-mitm
Also it looks like you did not follow the installation instructions correctly. DO NOT use `sudo`

**Comment by Gatopaint** [comment]
:I @trisk Well unfortunately from what it looks like i can't do any otherwise.

**Comment by Gatopaint** [comment]
gatopaint@gatopaint-VirtualBox:~/pokemon-go-mitm-node$ npm start

> pokemon-go-mitm@2.1.0 start /home/gatopaint/pokemon-go-mitm-node
> coffee example.logTraffic.coffee

Error: Cannot find module 'http-mitm-proxy'
  at Function.Module._resolveFilename (module.js:455:15)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.exports.run (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/home/gatopaint/pokemon-go-mitm-node/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! pokemon-go-mitm@2.1.0 start: `coffee example.logTraffic.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokemon-go-mitm@2.1.0 start script 'coffee example.logTraffic.coffee'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-go-mitm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee example.logTraffic.coffee
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-go-mitm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-go-mitm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gatopaint/pokemon-go-mitm-node/npm-debug.log

Nevermind, i am still able to, i reset the terminal but i can only make it here.

**Comment by Gatopaint** [comment]
i'm dumb. .-.
