### ISSUE TITLE
Syntax errors when compiling with square/wire

### ISSUE THREAD

**Issue by Aphoh** [AeonLucid/POGOProtos#41]
`Exception in thread "main" java.lang.IllegalStateException: Syntax error in POGOProtos/src/POGOProtos/Data/Battle/BattleAction.proto at 1:1: expected a word
    at com.squareup.wire.schema.internal.parser.ProtoParser.unexpected(ProtoParser.java:1086)
    at com.squareup.wire.schema.internal.parser.ProtoParser.unexpected(ProtoParser.java:1082)
    at com.squareup.wire.schema.internal.parser.ProtoParser.readWord(ProtoParser.java:883)
    at com.squareup.wire.schema.internal.parser.ProtoParser.readDeclaration(ProtoParser.java:105)
    at com.squareup.wire.schema.internal.parser.ProtoParser.readProtoFile(ProtoParser.java:82)
    at com.squareup.wire.schema.internal.parser.ProtoParser.parse(ProtoParser.java:34)
    at com.squareup.wire.schema.SchemaLoader.loadFromDirectories(SchemaLoader.java:146)
    at com.squareup.wire.schema.SchemaLoader.load(SchemaLoader.java:106)
    at com.squareup.wire.WireCompiler.compile(WireCompiler.java:211)
    at com.squareup.wire.WireCompiler.main(WireCompiler.java:126)`

This can be recreated by cloning square/wire, running mvn clean install, and using the generated jar as such

`java -jar wire-compiler-2.2.0-jar-with-dependencies.jar --proto_path=src/POGOProtos/ 
--java_out=generated-java/wire`

Let me know if there is any easy fix or if this is completely out of the scope of the library.

Thanks.

**Comment by Aphoh** [comment]
Doh, proto3 not supported completely yet.
